// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qogufosrejhceyxmxeou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvZ3Vmb3NyZWpoY2V5eG14ZW91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MjM5MTksImV4cCI6MjA2ODE5OTkxOX0.f8-AGIQj5iL-5tB5SUuEYuC7-5V22AZ_Z1WPF5o9U8c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});